version: "3.9"

services:
  db:
    image: postgres:15
    container_name: trello_db
    environment:
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello
      POSTGRES_DB: trello
    ports:
      - "5432:5432"
